apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.secret.namespace }}
type: Opaque
data:
  postgres-password: {{ .Values.secret.postgresPassword | b64enc }}
  replication-password: {{ .Values.secret.replicationPassword | b64enc }}
