postgresql:
  auth:
    existingSecret: postgresql-secrets
    username: "postgres"
    passwordKey: "postgres-password"
    replicationUser: "repl_user"
    replicationPasswordKey: "replication-password"

persistence:
  enabled: true
  size: 50Gi
  storageClass: "scalegrid-ebs-sc"

primary:
  service:
    name: eks2-postgresql
    type: ClusterIP
    port: 5432
  postgresqlConfiguration:
    hot_standby: "on"
    primary_conninfo: "host=eks1-postgresql.us-east-1.eks1.local user=repl_user password={{ .Values.postgresql.auth.replicationPasswordKey }}"

  replication:
    enabled: true
    replicaCount: 1
    synchronous: true
    replicationUser: repl_user
    replicationPassword: replicationpass
    externalMaster:
      host: "eks1-postgresql.us-east-1.eks1.local"
      port: 5432
readReplicas:
  enabled: true
  replicaCount: 2

