apiVersion: batch/v1
kind: Job
metadata:
  name: create-publication-job
  labels:
    app: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
        - name: postgresql
          image: bitnami/postgresql:latest
          command:
            - "sh"
            - "-c"
            - |
              psql -h eks1-postgres -U postgres -d postgres -c 'CREATE PUBLICATION my_publication FOR ALL TABLES;';
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: postgresqlPassword
      restartPolicy: Never
  backoffLimit: 4
