replicaCount: 1
global:
  storageClass: "scalegrid-ebs-sc"
  postgresql:
    auth:
      existingSecret: postgresql-secrets
      username: "postgres"
      passwordKey: "postgres-password"
      replicationUser: "repl_user"
      replicationPasswordKey: "replication-password"
persistence:
  enabled: true
  storageClass: "scalegrid-ebs-sc"
  size: 10Gi

primary:
  service:
    type: ClusterIP
  postgresqlConfiguration:
    wal_level: "replica"
    archive_mode: "on"
    archive_command: "cp %p /bitnami/postgresql/wal_archive/%f"
    max_wal_senders: "10"
    hot_standby: "on"
---
postgresql:
  auth:
    existingSecret: postgresql-secrets
    username: "postgres"
    passwordKey: "postgres-password"
    replicationUser: "repl_user"
    replicationPasswordKey: "replication-password"

persistence:
  enabled: true
  size: 10Gi
  storageClass: "scalegrid-ebs-sc"

primary:
  service:
    type: ClusterIP
  postgresqlConfiguration:
    wal_level: "replica"
    archive_mode: "on"
    archive_command: "cp %p /bitnami/postgresql/wal_archive/%f"
    max_wal_senders: "10"
    hot_standby: "on"

readReplicas:
  replicaCount: 0  # Set to 0 on the primary
